### ISSUE TITLE
normalization_values.h5 does not exist

### ISSUE THREAD

**Issue by jvpoulos** [ratschlab/dpsom#2]
I ran all the pre-processing steps in order, and then when I run eicu_preproc/save_model_inputs.py I get the error on line 75:

> FileNotFoundError: File ../data/time_grid/normalization_values.h5 does not exist

I searched the repo and couldn't find the script that produces this file.

In my ../data/time_grid/ folder I  have batch_*.h5

**Comment by mhueser** [comment]
Dear Jason,

the missing file was uploaded to the folder <data/time_grid/> in the repo.

Best regards,
Matthias H.
